#!/bin/bash
# Print the Homebrew formula for a released version.
# Usage: scripts/gen-formula.sh <github-owner> <version> <checksums.txt>
# checksums.txt = the file attached to the GitHub release (sha256  filename per line).
set -euo pipefail
OWNER="$1"; VERSION="$2"; SUMS="$3"
sha() { grep "whisperdrop-${VERSION}-$1.tar.gz" "$SUMS" | awk '{print $1}'; }
BASE="https://github.com/${OWNER}/whisperdrop/releases/download/v${VERSION}"
cat <<RUBY
# Generated by scripts/gen-formula.sh — do not edit by hand.
class Whisperdrop < Formula
  desc "Send and receive files over LAN or an encrypted tunnel, from the screen edge or the CLI"
  homepage "https://github.com/${OWNER}/whisperdrop"
  version "${VERSION}"

  on_macos do
    on_arm do
      url "${BASE}/whisperdrop-${VERSION}-aarch64-apple-darwin.tar.gz"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "${BASE}/whisperdrop-${VERSION}-x86_64-apple-darwin.tar.gz"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    url "${BASE}/whisperdrop-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "$(sha x86_64-unknown-linux-gnu)"
  end

  def install
    bin.install "whisperdrop"
  end

  def caveats
    <<~EOS
      Run \`whisperdrop\` to start the app (receiver + edge drop zone + tunnel),
      or use it from any shell:  whisperdrop send <file> --to <device|ip|group>
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/whisperdrop --version")
  end
end
RUBY
